// app/layout.tsx
import type { Metadata } from 'next'
import Link from 'next/link'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Museum Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            padding: '1rem 2rem',
            borderBottom: '1px solid #ccc',
            marginBottom: '2rem',
            backgroundColor: '#FFEB3B',
          }}
        >
          <Link href="/">
            <h1
              style={{
                margin: 0,
                cursor: 'pointer',
                color: '#333',
                fontSize: '2rem',
                fontWeight: '700',
              }}
            >
              Museum Demo
            </h1>
          </Link>
        </header>

        <main>{children}</main>
      </body>
    </html>
  )
}
